---
# tasks file for vector-role
- name: Get vector distrib
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.23.0/{{ vector_version }}.deb"
    dest: "./{{ vector_version }}"
    mode: 0644
- name: Install package
  become: true
  apt:
    deb: "./{{ vector_version }}"
  notify: Start vector service

